### ISSUE TITLE
Inline foreign string literals are no longer supported.

### ISSUE THREAD

**Issue by vixr** [pelotom/purescript-d3#15]
pulp build results in an error due to backwards-compatability breaking compiler changes:

```
psc: No files found using pattern: src/**/*.js
psc: No files found using pattern: bower_components/purescript-*/src/**/*.js
psc: It looks like you are trying to use a feature from a previous version of the compiler:
Inline foreign string literals are no longer supported.
at "/Users/vixr/projects/purescript/packages/purescript-d3/src/Axis.purs" (line 23, column 3)
* ERROR: Subcommand terminated with error code 1
```

**Comment by nwolverson** [comment]
There are other issues - see PR #14 - @pelotom any chance of merge?

**Comment by pelotom** [comment]
@nwolverson I will try to get to it tonight... iirc there were still some issues with making the examples work after going to purescript 0.7

**Comment by nwolverson** [comment]
There were, I submitted a PR for those too (https://github.com/pelotom/purescript-d3-examples/pull/10). And actually submitted a PR to @freebroccolo's PR branch - https://github.com/freebroccolo/purescript-d3/pull/1 - might want to look at merging that instead. However as I note to make things build had to rename `bind` and you may want to pick a better option.

**Comment by pelotom** [comment]
Should be fixed now!
